export const UNIVERSITIES = [
  "Maharashtra State Board of Technical University",
  "Dr. Babasaheb Ambedkar Marathwada University, Chhatrapati Sambhajinagar",
  "Dr. Babasaheb Ambedkar Technological University, Lonere",
  "Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth, Ratnagiri",
  "Dr. Panjabrao Deshmukh Krishi Vidyapeeth, Akola",
  "Kavikulaguru Kalidas Sanskrit University, Ramtek",
  "Maharashtra Animal & Fishery Sciences University, Nagpur",
  "Maharashtra University of Health Sciences, Nashik",
  "Mahatma Phule Krishi Vidyapeeth, Rahuri",
  "Vasantrao Naik Marathwada Krishi Vidyapeeth, Parbhani",
  "University of Mumbai",
  "Kavayitri Bahinabai Chaudhari North Maharashtra University, Jalgaon",
  "Savitribai Phule Pune University",
  "Sant Gadge Baba Amravati University",
  "Shivaji University, Kolhapur",
  "Smt. Nathibai Damodar Thackersey Women's University, Mumbai",
  "Punyashlok Ahilyadevi Holkar Solapur University",
  "Swami Ramanand Teerth Marathwada University, Nanded",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "Gondwana University, Gadchiroli",
  "Maharashtra National Law University, Nagpur",
  "Maharashtra National Law University, Mumbai",
  "Maharashtra National Law University, Chhatrapati Sambhajinagar",
  "Dr. Homi Bhabha State University, Mumbai",
  "Hyderabad (Sind) National Collegiate University",
  "Maharashtra State Skills University",
  "COEP Technological University",
  "Karmaveer Bhaurao Patil University",
  "Laxminarayan Innovation Technological (LIT) University",
  "Sandip University",
  "Ajeenkya D Y Patil University",
  "Vishwakarma University",
  "MIT Art, Design and Technology University, Pune",
  "Dr. Vishwanath Karad MIT World Peace University",
  "Sanjay Ghodawat University, Kolhapur",
  "Symbiosis Skills and Professional University",
  "D Y Patil International University",
  "Chhatrapati Shivaji Maharaj University",
  "Spicer Adventist University",
  "Amity University Mumbai",
  "Somaiya Vidyavihar University, Mumbai",
  "Vijaybhoomi University",
  "G H Raisoni University, Amravati",
  "MGM University",
  "D Y Patil University Pune",
  "Sri Balaji University, Pune",
  "ATLAS SkillTech University",
  "D Y Patil Agriculture and Technical University",
  "FLAME University",
  "NICMAR University, Pune",
  "ITM Skills University",
  "Dr. P A Inamdar University",
  "JSPM University",
  "Pimpri Chinchwad University",
  "Universal AI University",
  "DES Pune University",
  "MIT Vishwaprayag University",
  "Ramdeobaba University",
  "Sanjivani University",
  "GH Raisoni International Skill Tech University",
  "Dr. D.Y. Patil Dnyan Prasad University",
  "ALARD University, Pune",
  "Indira University",
  "SVKM NMIMS Global University",
  "Universal Skilltech University",
  "Atharva University",
  "G H Raisoni Skill Tech University Nagpur",
  "Yashwantrao Chavan Maharashtra Open University",
  "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya, Wardha",
  "Indian Institute of Science Education & Research (IISER), Pune",
  "Indian Institute of Technology, Bombay",
  "Visvesvaraya National Institute of Technology, Nagpur",
  "Indian Institute of Information Technology, Pune",
  "Indian Institute of Information Technology, Nagpur",
  "Indian Institute of Management, Nagpur",
  "All India Institute of Medical Sciences, Nagpur",
  "Indian Institute of Management, Mumbai",
  "Central Institute of Fisheries Education, Mumbai",
  "Defence Institute of Advanced Technology, Pune",
  "Homi Bhabha National Institute, Mumbai",
  "Indira Gandhi Institute of Development Research, Mumbai",
  "Institute of Chemical Technology, Mumbai",
  "International Institute for Population Sciences, Mumbai",
  "Tata Institute of Fundamental Research, Mumbai",
  "Deccan College Postgraduate & Research Institute, Pune",
  "Gokhale Institute of Politics & Economics, Pune",
  "Tata Institute of Social Sciences, Mumbai",
  "Tilak Maharashtra Vidyapeeth, Pune",
  "Bharati Vidyapeeth, Pune",
  "D.Y. Patil Educational Society, Kolhapur",
  "Datta Meghe Institute of Higher Education & Research, Nagpur",
  "Dr. D.Y. Patil Vidyapeeth, Pune",
  "Krishna Vishwa Vidyapeeth, Karad",
  "MGM Institute of Health Sciences, Navi Mumbai",
  "SVKM's Narsee Monjee Institute of Management Studies (NMIMS), Mumbai",
  "Padmashree Dr. D. Y. Patil Vidyapeeth, Mumbai",
  "Pravara Institute of Medical Sciences, Ahmednagar",
  "Symbiosis International (Deemed University), Pune",
];

export const COLLEGES_BY_UNIVERSITY = {
  "University of Mumbai": [
    "H.R. College of Commerce & Economics, 123, Dinshaw Wachha Road, Churchgate, Mumbai",
    "K.J. Somaiya College of Science and Commerce, Vidyavihar, Mumbai-400 077",
    "Nagindas Khandwala College of Commerce, Arts & Management Studies and Shantaben Nagindas Khandwala College of Science, Bhavishya Bharat Campus, Bhadran Nagar, Off. S.V. Road, Malad (West), Mumbai-400 064",
    "K.J. Somaiya Comprehensive College of Education, Training and Research, Vidya Vihar, Mumbai - 400 077",
    "Ramnarain Ruia College, Matunga, Mumbai-400 019 (MS)",
    "B.K. Birla College of Arts Science & Commerce, B.K. Birla College Road, Kalyan, Dist., Thane-421 304 Maharashtra",
    "Jai Hind College Basantsing Institute of Science & J.T. Lalvani College of Commerce, 23-24 Backbay Reclamation, A-Road, Churchgate, Mumbai-400 020",
    "R.J. College of Arts, Science & Commerce, Opp. Railway Station, Mumbai-400 086 (Maharashtra)",
    "Rayat Sikhshan Sansthan's Karmaveer Bhaurao Patil College, Sector-15A, Vashi, Navi Mumbai-400 703",
    "Shri Vile Parle Kelavani Mandal's Mithibai College of Arts, Chauhan Institute of Amrutben Jivanlal College of Commerce and Economics, Vile Parle (West), Mumbai-400 056",
    "SIES College of Arts, Science & Commerce, Plot 83/84 & 106/107 Sion (West) Mumbai-400 002 (MS)",
    "Changu Kana Thakur Arts Commerce and Science College, New Panvel, Plot No. -1, Sector- 11, Colony, New Panvel (W), Dist., Raigad, Maharashtra-410 206",
    "Devrukh Shikshan Prasarak Mandal's Nyayadhish Tatyasaheb Athalye Arts, Vedmuti S.R. Sapre Commerce & Vidhidnya Dadasaheb Pitre Science College, At-Post-Devrukh, Taluka-Sangmeshwar Dist., Ratnagiri-415 804 Maharashtra",
    "Guru Nanak Khalsa College of Arts Science & Commerce, King's Circle, Matunga, Mumbai-400 019 Maharashtra",
    "Hansraj Jivandas College of Education, Dr. Madhuri Shah Campus, R.K. Mission Marg, Mumbai-400 052",
    "Kandivli Education Society's B.K. Shroff College of Arts & M.H. Shroff College of Commerce, Bhulabhai Desai Road, Kandivli (West) Mumbai Maharashtra-400 067",
    "MES Pillai College of Arts Commerce and Science, Sector- 16, New Panvel, Mumbai, Maharashtra-410 206",
    "R.A. Podar College of Commerce & Economics, Matunga, Mumbai- 400 019 Maharashtra",
    "Thakur College of Science & Commerce, Shyamnarayan Thakur Marg, Thakur Village, Kandivali (E), Mumbai-400 101",
    "Model College, Khambalpada, Near R.B.T. School, Thakurli (E), Dombivli-421 201 MS",
    "Shri Vile Parle Kelavani Mandal's Narsee Monjee College of Commerce & Economics, Juhu Scheme, Vile Parle (West) Mumbai-400 056 Maharashtra",
    "Kelkar Education Trust's Vinayak Ganesh Vaze College of Arts, Science and Commerce, Mithagar Road, Mulund East, Mumbai-400 081 (Maharashtra)",
    "M.M. College of Arts, N.M. Institute of Science & HRJ College of Commerce (Bhavan's College), JP Road, Munshi Nagar, Andheri (W), Mumbai-400 058 Maharashtra",
    "SIES College of Commerce & Economics, Plot No. 71/72, Sion Matunga Estate, T.V. Chidambaran Marg, Sion (East), Mumbai-400 022",
    "Vidya Prasarak Mandal's B.N. Bandodkar College of Science, Thane-400 601 Maharashtra",
    "VPM's K.G. Joshi College of Arts and N.G. Bedekar College of Commerce, Chendani, Bundar Road, Thane-West-400 606 Maharashtra",
    "Sanskar Sarjan Education Society's Dhirajlal Talakchand Sankalchand Shah College of Commerce, Kurar Village, Malad (East), Mumbai-400097 Maharashtra",
    "Dombivli Shikshan Prasarak Mandal's K.V. Pendharkar College of Arts, Science and Commerce, Dombivli (East), Plot No. SPL-4, Opposite MIDC Office, Dombivli (East), Dist- Thane, Maharashtra 421203",
    "Parle Tilak Vidyalaya Associations' Mulund College of Commerce, S.N. Road, Mulund West, Mumbai-400 080 Maharashtra",
    "Parle Tilak Vidyalaya Association's Sathaye College, Dixit Road, Vile Parle (E), Mumbai-400 057, Maharashtra",
    "Ramanand Arya D.A.V. College, Veer Savarkar Marg, Bhandup East, Mumbai, Maharashtra-400 042",
    "Smt. Kapila Khandvala College of Education, Juhu Road, Santacruz (W), Mumbai-400 054 Maharashtra",
    "Tolani College of Commerce, 150-151, Sher-E-Punjab Society, Guru Gobind Singh Road, Andheri (East), Mumbai- 400 093",
    "Vivekanand Education Society's College of Arts, Science & Commerce, Sindhi Society, Chembur, Mumbai-400 071 Maharashtra",
    "Wilson College, Girgaon Chowpatty, Mumbai-400 007 Maharashtra",
    "St. Xavier's Institute of Education, 40-A, New Marine Lines, Churchgate, Mumbai-400 020 MS",
    "Chetana's Hazarimal Somani College of Commerce & Economics, Smt. Kusumtai Chaudhari College of Arts, Survey No. 341, Near Government Colony, Bandra (E), Mumbai-400 051 Maharashtra",
    "D.E Society's Kirti M. Doongursee College of Arts, Science & Commerce, Kashinath Dhuru Road, Off. Veer Savarkar Marg, Dadar West, Mumbai-400 028, MS",
    "K.P.B. Hinduja College of Commerce, 315, New Charni Road, Opera House, Mumbai-400 004, MS",
    "R.P. Gogate College of Arts and Science and R.V. Jogalekar College of Commerce, Ratnagiri, Adv. NV Joshi Road, Near Dist. Court, Ratnagiri-415 612 Maharashtra",
    "Shri Pancham Khemraj Mahavidyalaya, Moti Talao Road, Sawantwadi, Maharashtra-416510",
    "SIES (Nerul) College of Arts Science and Commerce, Nerul East, Navi Mumbai-400 076 Maharashtra",
    "S.I.W.S. N.R. Swamy College of Commerce & Economics and Smt. Thirumalai College of Science, Plot No. 337, Sewri-Wadala Estate, Major R. Parameshwaran Marg, Wadala, Mumbai-400 031",
    "Bunts Sangha's S. M. Shetty College of Science Commerce and Management Studies, Mumbai - 400076.",
    "Guru Nanak Vidyak Society's Guru Nanak College of Arts, Science and Commerce, G.T.B. Nagar, Mumbai - 400037",
    "Lala Lajpatrai College of Commerce and Economics, Lala Lajpatrai Marg, Mahalaxmi, Mumbai 400034",
    "Mahatma Education Society's Pillai's College of Education and Research, Chembur Naka, Mumbai - 400071",
    "Royal College of Arts, Science and Commerce, Ismail M. Kanga Campus, Near Bhaktivedanta Hospital, Mira Road East, Dist. Thane -401107.",
    "Sadhana Education Society's L. S. Raheja College of Arts and Commerce, Relief Road, Santacruz (West), Mumbai 400054.",
    "Seva Sadan's College of Education, Seva Sadan Marg, Opp. Central Hospital Ulhasnagar-421 003, Maharashtra.",
    "Shri Rajasthani Seva Sangh's, Smt. Parmeshwaridevi Durgadutt Tibrewala Lions Juhu College of Arts, Commerce & Science, Shriniwas Bagarka Marg, J.B. Nagar, Andheri (East), Mumbai - 400059, MS",
    "Vivek College of Commerce, Goregaon (West), Vivek College Road, Siddharth Nagar, Goregaon West, Mumbai - 400104",
    "Shri Vile Parle Kelavani Mandal's Usha Pravin Gandhi College of Arts, Science and Commerce, Bhakti Vedanta Swami Marg, North-South Road No 1, Juhu Scheme, Vile Parle (West), Mumbai 400056.",
    "Sheth T.J. Education Society's Sheth Nanjibhai Khimjibhai Thakkar Thanawala College of Commerce and Sheth Jayantilal Tribhovandas Thanawala College of Arts, Near CKP Hall, Kharkar Ali, Thane (West) 400601.",
    "M.L. Dahanukar College of Commerce, Dixit Road, Vile Parle East, Mumbai 400057.",
    "Smt. Chandibai Himathmal Mansukhani College, Ulhasnagar, Near Railway Station, Smt. CHM College Road, Ulhasnagar - 421 003",
    "Rajasthani Sammelan Education Trust, Ghanshyamdas Saraf College of Arts & Commerce, RSET Campus, Swami Vivekanand Road, Malad West, Mumbai - 400 064",
    "Cosmopolitians Valia Chhaganlal Laljibhai College of Commerce and Valia Lilavantiben Chhaganlal College of Arts, D.N. Nagar, Cosmopolitan Education Society Road, Andheri (West), Mumbai 400053",
    "Nalanda Nritya Kala Mahavidyalaya, Plot A -7 / 1, N.S. Road No. 10, J.V.P.D. Scheme, Vile Parle (West), Mumbai - 400 049",
    "Chandrabhan Sharma College of Art, Commerce & Science, Adi Shankaracharya Marg, Powai-Vihar, Powai, Mumbai- 400 076",
    "K.J. Somaiya College of Arts and Commerce, Mumbai- 400 077",
    "Nes Ratnam College of Arts Science And Commerce, Nes Complex Lbs Marg Bhandup, West Mumbai 400078",
    "St. Xavier's College, Mumbai, 5, Mahapalika Marg, Dhobi Talao, Chhatrapati Shivaji Terminus Area, Fort, Mumbai, Maharashtra",
    "Aldel Education Trust St. John College of Humanities and Sciences, St. John Technical & Educational Campus, Vevoor, Manor Road, Palghar 401404",
    "Children Welfare Centre's Clara's College of Commerce, Versova, Andheri (West), Mumbai - 400061",
    "Dr. Datar Science, Dr. Behere Arts and Shri Pilukaka Joshi Commerce College, Chiplun, Dist. Ratnagiri - 415605",
    "Jeevan Jyot Educational Charitable Trust Reena Mehta College of Arts, Science, Commerce and Management Studies, Bhayandar (West), Dist. Thane - 401101, Maharashtra.",
    "Mahatma Education Society's Pillai HOC College of Arts, Science and Commerce, Taluka Khalapur, Dist. Raigad - 410 207",
    "Mahatma Education Society's Mahatma Night Degree College of Arts and Commerce, Chembur, Mumbai-400071",
    "Marwari Vidyala Sanchalit Smt. K. G. Mittal College of Arts & Commerce, Nahar Nagar, Malad West, Mumbai - 400064",
    "Matushri Kanbai Lalbai and Motibai Lohana Kanyashala and Balikagruh's B.L. Amlani College of Commerce and Economics, MR. Nathwani College of Arts, NS Road 06, next to Jamnabai school gate no. 4, JVPD scheme Vileparle West, Mumbai-400056",
    "Nirmala Memorial Foundation College of Commerce and Science, D.S. Road, Asha Nagar, Thakur Complex, Kandivali (East), Mumbai - 400101",
    "RAV's Laxmichand Golwala College of Commerce and Economics, RAV Campus. M, G. Road, Ghatkopar East 400077",
    "Smt. Mithibai Motiram Kundnani College of Commerce & Economics, T.P.S III, Bandra (W)-400050, Mumbai",
    "Tilak Education Society's S. K. College of Science and Commerce, Sector-25, Navi Mumbai-400706",
    "Tilak Education Society's J. K. College of Science and Commerce, Ghansoli, Navi Mumbai - 400701",
    "Tilak Education Society's Tilak College of Science and Commerce, Vashi, Navi Mumbai - 400703",
    "The S.I.A. College of Higher Education, P-88, MIDC Residential Area, Near Balaji Mandir, Dombivli (East)",
    "Shree Rahul College of Education, Mira Road -401107",
    "Prahladrai Dalmia Lions College of Commerce & Economics, Malad (West), Mumbai- 400064",
    "Pillai College of Education and Research, Raigad - 410206",
    "Khairul Islam Higher Education Society's Maharashtra College of Arts, Science and Commerce, Mumbai-400008",
    "Sophia College for Women, Bhulabhai Desai Road, Mumbai- 400 026 Maharashtra",
    "Chikitsak Samuha's Sir Sitaram and Lady Shantabai Patkar College of Arts and Science and V.P. Varde College of Commerce and Economics, SV Road, Goregaon (West), Mumbai-400 062",
  ],
  "Savitribai Phule Pune University": [
    "Symbiosis Society's College of Arts & Commerce, S.B. Road, Pune-411004",
    "Deccan Education Society's B.M. College of Commerce, 845, Shivajinagar, Pune-411 004",
    "Modern College of Arts, Science and Commerce, Shivajinagar, Pune- 411 005 Maharashtra",
    "Sir Parashurambhu College, Pune- 411 030 Dist., Pune Maharashtra",
    "T.C. College of Arts Science and Commerce, Baramati, Dist., Pune- 413 102 Maharashtra",
    "Sangamner Nagarpalika Arts, D.J. Malpani Commerce & B.N. Sarda Science College, Sangamner-422 605 Dist., Ahmednagar, Maharashtra",
    "SCES's Indira College of Commerce and Science, 89/2A, Dhruv, Thathawade, Pune-411 033",
    "M.C.E. Society's Abeda Inamdar Senior College of Arts, Science and Commerce, Pune 2390-B, K.B. Hidayatullah Road, Azam Campus, Camp Pune-411 001, MS",
    "All India Shri Shivaji Memorial Society's College of Hotel Management and Catering Technology, 55-56, Shivajinagar, Pune-411 005 Maharashtra",
    "M.E.S. Garware College of Commerce, Karve Road, Pune, Maharashtra-411 004",
    "New Arts, Commerce and Science College, Laltaki Road, Ahmednagar-414 001 Maharashtra",
    "Maharashtra Education's Society's Abasaheb Garware College, Karve Road, Pune-411 004, Maharashtra",
    "Progressive Education Society's Modern College of Arts, Science and Commerce, Gandeshkhind, Pune-411 016 Maharashtra",
    "Nowrosjee Wadia College, Pune, 19, Late Principal V.K. Joag Path, Pune-411 001 Maharashtra",
    "G H Raisoni Educational & Medical Foundation's G H Raisoni College of Arts, Commerce & Science, Pune Nagar Road, Wagholi, Tahasil: Haweli, Pune Dist., Pune, Maharashtra",
    "R.B. Narayanrao Borawake College, Shrirampur, Tal Shrirampur, Dist- Ahmednagar-413 709 Maharashtra",
    "Pune District Education Associations, Prof. Ramakrishna More Arts, Commerce and Science College, Akurdi, Pune, Sec No. 28, Gangadhar, Pradhikaran, Akurdi, Pune, Maharashtra",
    "MAEER's MIT Arts, Commerce and Science College, Alandi, Opposite to Gajanan Maharaj Temple, near Dehu Phata, Alandi (D).",
    "H.V. Desai Senior College of Arts, Science & Commerce, Budhwaar Peth, Pune 2",
    "St. Mira's College for Girls, 6, Koregaon Road, Pune- 411001.",
    "Maharaja Sayajirao Gaikwad Arts, Science, and Commerce College, Loknete Vyankatrao Hiray Marg, Malegaon Camp, Dist. Nashik 423105",
    "Mahatma Gandhi Vidyamandir's Arts, Commerce and Science College, Malegaon City, Qidwai Road, Malegaon Dist, Nashik",
    "Mahatma Gandhi Vidyamandir's Arts, Science & Commerce College, Nashik, 423104",
    "Tikaram Jagannath Arts, Commerce and Science College, 491, Elphinstone Road, Khadki, Pune - 411003",
    "Fergusson College, Pune-411 004 (Maharashtra)",
    "Loknete Vyankatrao Hiray Arts, Science and Commerce College, Nashik-03",
  ],
  "Shivaji University, Kolhapur": [
    "Chhatrapati Shahu Institute of Business Education & Research, University Road, Kolhapur-416004 (Maharashtra)",
    "Dhananjayrao Godgil College of Commerce, Satara Maharashtra-415 001",
    "Vivekanand College, 2130/E, Tarabai Park, Kolhapur-416 003 (Maharashtra)",
    "Chhatrapati Shivaji College, Satara, Maharashtra-415 001",
    "Sadguru Gadge Maharaj College, Karad, Dist., Satara Maharashtra",
    "Deshbhakta Ratnappa Kumbhar College of Commerce, Dist., Kolhapur-416 002, MS",
    "Kamala College, Rajarampuri, 1 Lane, Kolhapur-416 008 Maharashtra",
    "Mahavir Mahavidyalaya, 7/E, Vaishali Parisar, Bhausinji Road, Nagala Park, Kolhapur-416 003 Maharashtra",
    "Night College of Arts And Commerce, Bindu Chowk, Ravivar Peth, Kolhapur, Maharashtra",
    "Yashvantrao Chavan Institute of Science, Satara, 533, Sadar Bazar, Satara Maharashtra-415 001",
  ],
  "Sant Gadge Baba Amravati University": [
    "H.V.P. Mandal's Degree College of Physical Education, Hanuman Vyayam Nagar, Amravati",
    "Vidya Bharati Mahavidyalaya, C.K. Naidu Road, Camp, Amravati",
    "Government Vidarbha Institute of Science and Humanities, Amravati 444 604",
  ],
  "Rashtrasant Tukadoji Maharaj Nagpur University": [
    "St. Vincent Pallotti College of Engineering and Technology, Nagpur",
    "Tulsiramji Gaikwad-Patil College of Engineering and Technology, Nagpur",
    "Jankidevi Bajaj College of Science, Jamnalal Bajaj Marg, Civil Lines, Wardha, Maharashtra-442 001",
    "G.S. College of Commerce & Economics, Nagpur, Civil Lines, Amravati Road, Nagpur- 440 001, Maharashtra",
    "Institute of Science, R.T. Road, Civil Lines, Nagpur-440 001, Maharashtra",
    "G.H. Raisoni College of Commerce, Science & Technology, Maharashtra",
    "G.S. College of Commerce, Wardha, Jamnalal Bajaj Marg, Civil Lines, Wardha, Maharashtra, India - 442001",
    "Government Institute of Forensic Science Nagpur, Institute of Science Campus, R T Road, Civil Lines Nagpur",
    "Shri Binzani City College, Umred Rd, Sakkardara Rd, Raghuji Nagar, Nagpur- 440024",
  ],
  "Kavayitri Bahinabai Chaudhari North Maharashtra University, Jalgaon": [
    "Bhusawal Arts, Science and P.O. Nahata Commerce College, Ah-4, Across, Jamner Road, Bhusawal-425 201, (Maharashtra)",
    "KEM's Pratap College, Amalner, Tal. Amalner, Dist., Jalgaon Maharashtra",
    "Moolji Jaitha College, Shivram Nagar, Prabhat Colony, Jalgaon, Maharashtra 425001",
    "Khandesh College Education Society's College of Education and Physical Education, Jalgaon, TPS III, Plot No 2, Building No 17, M.J. College Campus, Jilha Peth, Jalgaon, Maharashtra, 425002",
    "Dhanaji Nana Chaudhuri Vidya Prabodhini's College of Social Work, Jalgaon",
    "Dr. Annasaheb G.D. Bendale Mahila Mahavidyalaya, Jilhi Road, Jilha Peth, Jalgaon, Maharashtra",
  ],
  "Smt. Nathibai Damodar Thackersey Women's University, Mumbai": [
    "S.V.T. College of Home Science, Juhu, Mumbai (Maharashtra)",
    "Dr. Bhanuben Mahendra Nanavati College of Home Science, Matunga, Mumbai-400 019 Maharashtra",
    "Smt. Maniben M.P. Shah Women's College of Arts & Commerce, Matunga, Dist., Mumbai-400 019 Maharashtra",
    "Sadabai Raisoni Women's College, Khasar No. 50, Near CRPF Gate No. 3, Madhav Nagri, Nagpur-440 016 Maharashtra",
    "Shri M. D. Shah Mahila College of Arts and Commerce, B. J. Patel Road, Malad (West), Mumbai 400064",
    "Maniben Nanavati Women's College, Mumbai-400056",
    "Smt. P. N. Doshi Women's College of Arts, Kum. U. R. Shah Women's College of Commerce and Dr. (Smt.) Nanavati Bhanuben Mahendra Women's College of Home Science, Mumbai - 400086",
  ],
  "Swami Ramanand Teerth Marathwada University, Nanded": [
    "Rajarshi Shahu College, Latur - 413512 (M.S.)",
  ],
  "Dr. Babasaheb Ambedkar Marathwada University, Chhatrapati Sambhajinagar": [
    "Govt. College of Arts & Science, Aurangabad - 431 001",
    "Marathwada Shikshan Prasarkar Mandal's Deogiri College, Aurangabad-431005",
  ],
  "Punyashlok Ahilyadevi Holkar Solapur University": [
    "Sangameshwar College, Solapur, 164, Railway Lines, Saat Rasta, Solapur-413 001 Maharashtra",
    "Walchand College of Arts and Science, Solapur, WH Marg, Ashok Chowk, Solapur-413 006",
    "Hirachand Nemchand College of Commerce, Seth Walchand Hirachand Marg, Ashok Chowk, Solapur-413 006 Maharashtra",
    "Karmaveer Bhaurao Patil Mahavidyalaya, Karmaveer Path, Pandharpur-413 304 Dist., Solapur Maharashtra",
  ],
};